[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
gas_reports = ["ACP99Manager", "AvalancheICTTRouter"]

[fmt]
line_length = 100
multiline_func_header = "params_first"
single_line_statement_blocks = "multi"
sort_imports = true
override_spacing = true
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
